# Generated by Django 5.2 on 2025-04-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountyCurrent',
            fields=[
                ('state_territory', models.TextField(db_column='State')),
                ('sewershed_id', models.TextField(db_column='Sewershed_ID', primary_key=True, serialize=False)),
                ('counties_served', models.TextField(db_column='Counties_Served')),
                ('population_served', models.FloatField(db_column='Population_Served')),
                ('wval_category', models.TextField(db_column='WVAL_Category')),
                ('reporting_week', models.TextField(db_column='Reporting_Week')),
            ],
            options={
                'db_table': 'county_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('week_1_prediction', models.FloatField()),
                ('week_2_prediction', models.FloatField()),
                ('week_3_prediction', models.FloatField()),
                ('week_4_prediction', models.FloatField()),
            ],
            options={
                'db_table': 'future_predictions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateTimeseries',
            fields=[
                ('pk', models.CompositePrimaryKey('state_territory', 'ending_date', blank=True, editable=False, primary_key=True, serialize=False)),
                ('state_territory', models.TextField(db_column='State')),
                ('ending_date', models.DateField(db_column='Ending_Date')),
                ('data_collection_period', models.TextField(db_column='Data_Collection_Period')),
                ('state_territory_wval', models.FloatField(db_column='State_WVAL')),
                ('national_wval', models.FloatField(db_column='National_WVAL')),
                ('regional_wval', models.FloatField(db_column='Regional_WVAL')),
                ('wval_category', models.TextField(db_column='WVAL_Category')),
                ('coverage', models.TextField(db_column='Coverage')),
            ],
            options={
                'db_table': 'state_timeseries',
                'managed': False,
            },
        ),
    ]
